### ISSUE TITLE
Create an ADR for uds-security-hub-scanning

### ISSUE THREAD

**Issue by koesbong** [defenseunicorns/uds-security-hub-v1-archive#176]
It would be very helpful to give folks some context on the decision to move scanning to its own repository.

**Comment by partkyle** [comment]
1 reason is the releases are where we store the cosign signature. Releases would not be usable in uds-security-hub since we already use that for the binary releases.

If we were to move that to s3 or ghcr alongside the database, maybe we don't need the release system.

I'm not sure if there is another reason for uds-security-hub-scanning.
