### ISSUE TITLE
Add JSON export to S3 bucket functionality for scan reports

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-security-hub-v1-archive#222]
The [LULA](https://github.com/defenseunicorns/lula) project needs to consume our scan reports in JSON format.

**Comment by naveensrinivasan** [comment]
@brandtkeller 👀

**Comment by brandtkeller** [comment]
Appreciate this issue being created. 

Lula having access to individual (point-in-time) scans in JSON format is something we may be able to support in the near future. 

If we additionally had the historical data in JSON format - Lula could begin to codify something like CVE response SLA.

**Comment by naveensrinivasan** [comment]
>Lula having access to individual (point-in-time) scans in JSON format is something we may be able to support in the near future.

@brandtkeller 
  Can you please expand on this? We have the capability to get scan results as JSON.

**Comment by brandtkeller** [comment]
Adding that for context - as I understand it today, uds-security-hub can scan a single and provide JSON format for a single scan. 

The request or missing piece is including a workflow for exporting the data important to the company (many packages & many scans) to a JSON format and placing that in an accessible location. 

Does that align with your thoughts?

**Comment by marshall007** [comment]
@naveensrinivasan should we consider publishing the SQLite database and/or any other report formats as an OCI image? This is how Trivy distributes their vulnerability database: https://github.com/aquasecurity/trivy-db#download-the-vulnerability-database

It can be pulled using the Trivy CLI (obviously) or directly with `oras`:

```
oras pull ghcr.io/aquasecurity/trivy-db:2
```

This would get you versioning for free. It also simplifies providing multiple formats (different image tags?) and makes signing/verification easier. Perhaps most importantly, it would simplify bringing the db to air-gapped environments because it could be bundled as an image in a zarf package.
